export const LOAD_USERS_REQUEST = "LOAD_USERS_REQUEST";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_USERS_FAIL = "LOAD_USERS_FAIL";

export const LOAD_USER_DETAILS_REQUEST = "LOAD_USER_DETAILS_REQUEST";
export const LOAD_USER_DETAILS_SUCCESS = "LOAD_USER_DETAILS_SUCCESS";
export const LOAD_USER_DETAILS_FAIL = "LOAD_USER_DETAILS_FAIL";

export const SINGLE_USER_DELETE_REQUEST = "SINGLE_USER_DELETE_REQUEST";
export const SINGLE_USER_DELETE_SUCCESS = "SINGLE_USER_DELETE_SUCCESS";
export const SINGLE_USER_DELETE_FAIL = "SINGLE_USER_DELETE_FAIL";

export const UPDATE_USER_ROLE_REQUEST = "UPDATE_USER_ROLE_REQUEST";
export const UPDATE_USER_ROLE_SUCCESS = "UPDATE_USER_ROLE_SUCCESS";
export const UPDATE_USER_ROLE_FAIL = "UPDATE_USER_ROLE_FAIL";